version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes: 
      - ./client:/usr/src/app/client
      - node_modules:/usr/src/app/client/node_modules
    

  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - node_modules_b:/usr/src/app/node_modules
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes: 
  node_modules:
  node_modules_b:
  data:
    


  